# Generated by Django 4.0.4 on 2022-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
